### PR TITLE
make the bot better

### PR DESCRIPTION
**Pull request by celestialgaze3**
**basically what this code does is it makes the bot better and adds a lot of new features that are demanded by users on the regular**

### CODE REVIEW

**Comment by celestialgaze3** [comment]
fix it

**Comment by celestialgaze3** [comment]
fix the conflcis

**Comment by celestialgaze3** [comment]
i resolved thmed

**Comment by celestialgaze3** [comment]
make i better

**Comment by tapnisu** [comment]
bruh

**Comment by LiterallyLink** [comment]
> bruh

he's a friend, don't worry lmao.

**Comment by celestialgaze3** [comment]
not fixewd

**Comment by celestialgaze3** [comment]
fix it now

**Comment by celestialgaze3** [comment]
open coward

**Pull request closed without merging**
